version: '3.9'
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    shm_size: 1g
    ports:
      - '5432:5432'
    volumes:
      - $PWD/docker_volumes/data:/docker_volumes/data
    environment:
      - POSTGRES_DB=service_matcher
      - POSTGRES_USER=app_admin
      - POSTGRES_PASSWORD=1234abc
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c max_connections=200 -c statement_timeout=60s -c idle_in_transaction_session_timeout=60s
    restart: on-failure

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  redis:
    image: 'redis:6.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  data:
